### ISSUE TITLE
OctoPrint Printerprofile inverted Axis are ignored

### ISSUE THREAD

**Issue by rmayergfx** [jakebullet70/OctoTouchController#31]
Inside Octoprint i have to invert the Y axis to match the movement.
OctoTC is connected to this instance with api, but ignored the settings to invert this axis.

So on the Display the movement is different to the setup.

Please add the option to invert the axis or read the flag from octoprint setup.

**Comment by jakebullet70** [comment]
I will look at that in my morning.

**Comment by jakebullet70** [comment]
Fixed, will be out in the next release this week.

**Comment by rmayergfx** [comment]
Thx. it is working fine now on all axis.

**Comment by jakebullet70** [comment]
Fixed

**Comment by rmayergfx** [comment]
Sorry, needs to be reopened. I don´t know why, but after Printing and Homing e.g. from PC Webinterface the axis Y and Z are again inverted.

**Comment by jakebullet70** [comment]
OK, thats strange, when OctoTouchController starts it reads the values for the inverted flag and saves them. It then uses those values. It never reads then a second time. I will try some more testing - I reopen this.

**Comment by jakebullet70** [comment]
Are you saying though they are always working correctly from the Octoprint web interface?

**Comment by rmayergfx** [comment]
Yes. from PC or any other device connected via Webbrowser it is always working fine. Find the issue after printjob was finished and i tried to move the bed forward to easy pull of the print and the printer was doing nothing, so i tried the "wrong" direction and the bed slides to me. so i don´t know why and how this is happening.  When it is wrong, also Z is wrong but Z is not inverted. Only x axis stays fine.

**Comment by jakebullet70** [comment]
Found a place where there could be an issue: I am testing.

**Comment by jakebullet70** [comment]
I have release V1.29 - We no longer read inverted information from Octoprint. This is now set up locally in the General Options screen in the app.

**Comment by jakebullet70** [comment]
Is this now working?

**Comment by jakebullet70** [comment]
fixed
