### ISSUE TITLE
Please add option to use another Plugin

### ISSUE THREAD

**Issue by rmayergfx** [jakebullet70/OctoTouchController#32]
Is it possible to add: https://github.com/jneilliii/OctoPrint-BedLevelingWizard

Would be great

**Comment by rmayergfx** [comment]
Sorry, don´t know what you mean....plz explain

**Comment by jakebullet70** [comment]
No worries, I created it --> issue:  #33
If you comment on it, you will get notified when it's done.

**Comment by jakebullet70** [comment]
Moved to #33
