### ISSUE TITLE
Red Cross on Printig page after start

### ISSUE THREAD

**Issue by rmayergfx** [jakebullet70/OctoTouchController#35]
i always get an red X on the right side after pressing the Printing Button.
Can you explain why? Pressing on this red X in the square changes to the temperature view.

How can i get off the red X together with octoprint or is it possible to set in the settings default to show the temperatur as default?

**Comment by jakebullet70** [comment]
The Red X is no thumbnail.  Do you have thumbnails enabled in your slicer?

**Comment by jakebullet70** [comment]
Good idea though to make it optional and go to the temp screen. I will add it as an option.

**Comment by jakebullet70** [comment]
Oh, found a bug where the red X could get stuck (even if you have thumbnails on) depending on how the print was started. Fixed.

**Comment by rmayergfx** [comment]
on which release?

**Comment by jakebullet70** [comment]
I will be putting out a new release in the next few days. it will have the red x fix and the new bed leveling wizard.

**Comment by jakebullet70** [comment]
V1.3.0 has been released.
