### ISSUE TITLE
phone won't connect too the Server 

### ISSUE THREAD

**Issue by Justus123123** [jakebullet70/OctoTouchController#55]
I downloaded the app onto my phone and tried too connect it, but it don't worked. I think i need to download something onto the Server but i don't know what and how.  Octoklipper is Downloaded

**Comment by jakebullet70** [comment]
Octoklipper is a plugin for Octoprint that allows Octoprint to talk to Klipper based printers. If you are running Octoprint and your printer firmware is Klipper then this plugin needs to be installed 1st. 

https://plugins.octoprint.org/plugins/klipper/

**Comment by Justus123123** [comment]
thank you but the Plugin was enabled before

**Comment by jakebullet70** [comment]
OK, so OctoKlipper is installed and working. 

What version of Octoprint are you using? 
What version of Android?

When you enter the 'printer connection' screen on your android device and touch the 'request Octoprint Key' button are you then checking your octoprint web page on your computer? It should then ask you to accept request?

 
![image](https://github.com/jakebullet70/OctoTouchController/assets/14124210/d92aa928-2b95-4bdc-949a-2f931be5b0bc)

And staying as safe as possible!  :)

**Comment by Justus123123** [comment]
Its the latest octoprint Version and android 13.And when i press request octoprint key. The app says couldn't find the server

**Comment by jakebullet70** [comment]
Ahhhhhh, OK its Android 13. Google did a Google and broke a lot of previously running programs with the Android 13 release. The did the same with the Android 10 release too so your phone is not going to work. So you have a couple of options.

1. Head over to the Android store and there are some good Octoprint programs out there. I would try one of those. 
2. Buy an old phone. I just bought an old Android phone for $6. (Samsung G350E)  Its running Android 4.4 and works fine with my software. Any phone / tablet running Android 4  - 7 have been tested. 

I will update the main page here to let uses know it will not work with newer Android devices.

I have no plan to play Googles game with their changing Android versions and honestly my program was mostly written to reuse older Android phones and tablets to keep them out of the trash.  :)

**Comment by Justus123123** [comment]
Thank you, but the App itself is running perfectly.But then there is the problem.

**Comment by jakebullet70** [comment]
As I understand there were changes to Android's networking and permissions. Unfortunately, I do not have an Android 13 device.
